    ~^/index.php    'yes';
    ~^/wp-admin/              'yes';
    ~^/wp-includes/           'yes';
    ~^/index.php              'yes';
    ~^/xmlrpc.php             'yes';
    ~^/wp-login.php           'yes';
    ~^/wp-register.php        'yes';
    ~^/wp-comments-post.php   'yes';
    ~^/wp-cron.php            'yes';
    ~^/wp-load.php            'yes';
    ~^/wp-signup.php          'yes';
